[application]
name = "frontend"
default_platform = "web"

[web.app]
title = "OAuth App"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = ["assets/main.css"]

[web.resource.dev]
style = []

[[web.proxy]]
backend = "http://localhost:3000/api/"
