// AUTOGENERATED Components module
// `dx components` registridan ko'chirilgan kod — barcha variant/o'lchamlar
// hozircha ishlatilmasa ham kutubxona sifatida to'liq qoladi.
#![allow(dead_code)]

pub mod input;
pub mod card;
pub mod button;
pub mod label;
pub mod separator;
